spring.application.name=explainabilityservice
server.port=8087
spring.data.mongodb.uri=mongodb://localhost:27017/explainabilitydb
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true