spring.application.name=modelservice
server.port=8088
spring.data.mongodb.uri=mongodb://localhost:27017/modeldb
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true